name: CI for develop PR

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Prettier
        run: npx prettier --check .

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - run: npm ci
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
      - name: Build Android Debug
        run: cd android && ./gradlew assembleDebug

  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ios/Podfile.lock
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      - run: npm ci
      - uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: '1.16.2'
      - name: Install Pods
        run: cd ios && pod install
      - name: Build iOS Debug
        run: cd ios && xcodebuild -workspace ppu_frontend.xcworkspace -scheme ppu_frontend -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

  discord-notify:
    runs-on: ubuntu-latest
    needs: [lint-and-prettier, android-build, ios-build]
    if: github.event_name == 'pull_request'
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "📢 새로운 PR이 열렸어요!\n'"$PR_URL"'"}' \
            $DISCORD_WEBHOOK
